"""Add column user_id in visitors

Revision ID: f5463622f46d
Revises: 5b43bccc8bf2
Create Date: 2025-01-08 17:22:04.688073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, Integer

# revision identifiers, used by Alembic.
revision: str = 'f5463622f46d'
down_revision: Union[str, None] = '5b43bccc8bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("visitors") as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.add_column(
            Column(
                'user_id',
                Integer,
                nullable=True,
            ),
        )
        batch_op.create_foreign_key(
            "fk_visitor_user_id_user",
            'users',
            ['user_id'],
            ['id'],
        )


def downgrade() -> None:
    naming_convention = {
        "fk":
            "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table(
            "visitors",
            naming_convention=naming_convention,
    ) as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.drop_constraint(constraint_name="fk_visitor_user_id_user", type_='foreignkey')
        batch_op.alter_column(
            'user_id',
            existing_type=sa.INTEGER(),
            nullable=False,
        )
        # ### end Alembic commands ###
